version: "3"
services:
    test:
        image: ${IMAGE_TAG}
        environment:
          - CONNECTION_STRING=Server=db;User ID=sa;Password=integration
          - DIALECT=SqlServer
        depends_on:
          - db
        command: --integration
        labels:
          - test
        links:
          - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
          - SA_PASSWORD="integration"
          - ACCEPT_EULA="Y"