version: "3"
services:
    test:
        image: ${IMAGE_TAG}
        environment:
          CONNECTION_STRING: "Host=db;User ID=postgres;Password=Integration123"
          DIALECT: "Postgres"
        depends_on:
          - db
        command: --integration
        labels:
          - test
        links:
          - db
    db:
        image: "postgres"
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_PASSWORD=Integration123